spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}
