# 데이터베이스
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/giwoot_jang_schema
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 시큐리티
  security:
    user:
      name: admin
      password: 1234