spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: ${ELASTIC_CACHE_PORT}
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PWD}

