# 데이터베이스
spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${MYSQL_ENDPOINT}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_ID}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 시큐리티
  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}
