name: Java CI with Gradle

on:
  push:
    branches: [ "feat/#27/Github-Actions-CI/CD" ]
  pull_request:
    branches: [ "develop" ]

env:
  APPLICATION_YAML: ${{ secrets.APPLICATION_YAML }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_ED25519_PEM: ${{ secrets.SSH_ED25519_PEM }}
  LOCAL_DB_PORT: ${{ secrets.LOCAL_DB_PORT }}
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  RDS_PORT: ${{ secrets.RDS_PORT }}
  DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_ID: ${{ secrets.DB_ID }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  SECURITY_NAME: ${{ secrets.SECURITY_NAME }}
  SECURITY_PASSWORD: ${{ secrets.SECURITY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Application.yaml
        shell: bash
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          echo "$APPLICATION_YAML" > application.yaml

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_ED25519_PEM" > ~/.ssh/id_ed
          chmod 600 ~/.ssh/id_ed
          ssh-keyscan -H ${SSH_HOST}>> ~/.ssh/known_hosts

      - name: Start SSH tunnel
        run: |
          nohup ssh -i ~/.ssh/id_ed -fN -L ${LOCAL_DB_PORT}:${RDS_ENDPOINT}:${RDS_PORT} ${SSH_USERNAME}@${SSH_HOST} &
          echo $! > ssh-tunnel.pid
          echo "SSH tunnel started with PID $(cat ssh-tunnel.pid)"

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Stop SSH tunnel
        if: always()
        run: |
          echo "Stopping SSH tunnel"
          if [ -f ssh-tunnel.pid ]; then
            PID=$(cat ssh-tunnel.pid)
            echo "Killing SSH tunnel with PID $PID"
            kill $PID || true
            sleep 2
            if pgrep -f "ssh -i ~/.ssh/id_ed -fN -L ${LOCAL_DB_PORT}:${RDS_ENDPOINT}:${RDS_PORT}" > /dev/null; then
              echo "SSH tunnel still running. Forcing termination."
              kill -9 $PID || true
            else
              echo "SSH tunnel stopped successfully"
            fi
            rm ssh-tunnel.pid
          else
            echo "No PID file found. SSH tunnel might not have been started."
          fi